blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path('', include('posts.urls', namespace="posts")),
]

blog/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/new/', views.group_new, name='create_group'),
    path('group/<int:pk>/edit/', views.group_edit, name='edit_group'),
    path("post/new/", views.new_post, name="create_post"),
    path("post/edit/<int:pk>/", views.edit_post, name="edit_post"),
]

blog/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import SignUp

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logout.html'),
        name='logout',
    ),
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(
        template_name='users/login.html'), name='login')
]

blog/posts/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MaxLengthValidator
from django.db import models

User = get_user_model()


class Group(models.Model):
    """ Модель для создания группы в соц.сети. """

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    """ Модель для создания поста в соц.сети. """
    topic = models.CharField(help_text="Введите тему поста", max_length=255, null=False)
    text = models.TextField(
        help_text="Введите текст поста",
        validators=[MaxLengthValidator(250, "Превышено максимальное количество символов")]
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts',
        help_text="Выберите группу поста"
    )

    class Meta:
        ordering = ('-pub_date',)

blog/users/models.py
from django.db import models

# Create your models here.

blog/posts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Group, Post


class GroupForm(forms.ModelForm):
    def clean_slug(self):
        cleaned_slug = self.cleaned_data["slug"].lower()
        if cleaned_slug == "new":
            raise ValidationError("A slug may not be a 'new'")
        return cleaned_slug

    class Meta:
        model = Group
        fields = ("title", "slug", "description")

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'})
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('topic', 'group', 'text')

        labels = {
            'text': 'Текст',
            'topic': "Тема",
            'group': 'Группа'
        }

        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
            'topic': "Тема поста"
        }

        widgets = {
            'topic': forms.TextInput(attrs={'class': 'form-control'}),
            'group': forms.Select(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'})
        }

    def clean_topic(self):
        cleaned_topic = self.cleaned_data["topic"].lower()
        if cleaned_topic == "new topic":
            raise ValidationError("A topic may not be a 'new'")
        return cleaned_topic

blog/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

blog/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings

from posts.forms import GroupForm, PostForm
from posts.models import Post, Group


def index(request):
    if request.method != "GET":
        return HttpResponseNotAllowed("GET")

    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.POSTS_PER_PAGE)

    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    context = {
        'page': page,
        'title': 'Последние обновления на сайте',
    }
    return render(request, 'posts/index.html', context)


def group_new(request):
    if request.method == "GET":
        form = GroupForm()
        return render(request, "posts/new_group.html", {"form": form})
    else:
        form = GroupForm(request.POST)
        if form.is_valid():
            new_group = form.save()
            return render(request, "posts/group_detail.html", {"group": new_group})
        return render(request, "posts/new_group.html", {"form": form})


@login_required
def group_edit(request, pk):
    group = get_object_or_404(Group, pk=pk)
    if request.method == "POST":
        bound_form = GroupForm(request.POST, instance=group)
        if bound_form.is_valid():
            group = bound_form.save()
            return render(request, 'posts/group_detail.html', {"group": group, "title": "Group detail form"})
    else:
        bound_form = GroupForm(instance=group)
        return render(request, 'posts/edit_group.html', {"form": bound_form, "title": "Group edit form", "group": group})


@login_required
def new_post(request):
    if not request.method == 'POST':
        form = PostForm()
        return render(
            request, "posts/new_post.html", {'form': form}
        )

    form = PostForm(request.POST)
    if not form.is_valid():
        return render(
            request, "posts/new_post.html", {'form': form}
        )
    post = form.save(commit=False)
    post.author = request.user
    post.save()

    return redirect('posts:index')


@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:index')

    context = {
        "form": form,
        "post": post
    }
    return render(request, "posts/edit_post.html", context=context)

blog/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("login")
    template_name = "users/signup.html"

blog/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <title>{{ title }}</title>
  </head>
  <body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

blog/templates/includes/footer.html
<!DOCTYPE html>
<html lang="ru">
    <body>
        <footer class="border-top text-center py-3">
          <p>© 2021 Copyright Blog</p>
        </footer>
    </body>
</html>

blog/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
    </a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            Пользователь: {{ user.username }}.
            <a class="p-2 text-dark" href="{% url 'posts:create_post' %}">Новая пост</a>
            <a class="p-2 text-dark" href="{% url 'posts:create_group' %}">Новая группа</a>
            <a class="p-2 text-dark" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'users:login' %}">Войти</a> |
            <a class="p-2 text-dark" href="{% url 'users:signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

blog/templates/includes/paginator.html
<nav aria-label="Переключение страниц">
    <ul class="pagination">
        {% if items.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ items.previous_page_number }}">&laquo; Предыдущая</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo; Предыдущая</a></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if items.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(текущая)</span></span></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if items.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ items.next_page_number }}">Следующая &raquo;</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Следующая &raquo;</a></li>
        {% endif %}
    </ul>
</nav>

blog/templates/posts/edit_group.html
{% extends 'base.html' %}
{% block title %}Редактирование группы{% endblock %}
{% block content %}
<div class="container py-5">
    <h1 style="text-align:center">{{ title }}</h1>
    <a href="{% url 'posts:create_group' %}">Перейти к форме создания группы</a><br>
    <form action="{% url 'posts:edit_group' group.pk %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}<br>
        <button type="submit" class="btn btn-primary">Редактировать группу</button>
    </form>
</div>
{% endblock %}

blog/templates/posts/edit_post.html
{% extends 'base.html' %}
{% block title %}Редактирование поста{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Редактировать пост</div>
            <div class="card-body">
                <form action="{% url 'posts:edit_post' post.pk %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group row my-3 p-3" aria-required="{% if field.field.required %}true{% else %}false{% endif %}">
                            <label for="{{ field.id_for_label }}">
                                {{ field.label }}
                                {% if field.field.required %}
                                  <span class="required text-danger">*</span>
                                {% endif %}
                            </label>

                            {{ field }}

                            {% if field.errors %}
                                <div class="alert alert-danger">
                                    {{ field.errors }}
                                </div>
                            {% endif %}

                            {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                    {{ field.help_text|safe }}
                                </small>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">Редактировать пост</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/posts/group_detail.html
{% extends 'base.html' %}
{% block title %}Карточка группы{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1 style="text-align:center">{{ title }}</h1>
        <a href="{% url 'posts:create_group' %}">Return to create form</a>
        <br>
        <dl class="row">
            <dt class="col-sm-3">Title</dt>
            <dd class="col-sm-9">{{ group.title }}</dd>

            <dt class="col-sm-3">Description</dt>
            <dd class="col-sm-9">{{ group.description }}</dd>

            <dt class="col-sm-3">Slug</dt>
            <dd class="col-sm-9">{{ group.slug }}</dd>
        </dl>
        <br>
        <a type="button button-primary" href="{% url 'posts:edit_group' group.pk %}">Edit Group</a>
    </div>
{% endblock %}

blog/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Главная страница{% endblock %}
{% block content %}
<div class="container py-5">
    <h1 style="text-align:center">{{ title }}</h1>
    <article>
    {% for post in page %}
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
            </li>
            <li>
                Дата публикации: {{ post.pub_date }}
            </li>
        </ul>
        <p>
            {{ post.text }}
        </p>
        <p>
            <a class="p-2 text-dark" href="{% url 'posts:edit_post' post.id %}">Редактировать пост</a>
        </p>
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% if page.has_other_pages %}
        {% include "includes/paginator.html" with items=page paginator=page.paginator %}
    {% endif %}
    </article><hr>
</div>
{% endblock %}

blog/templates/posts/new_group.html
{% extends 'base.html' %}
{% block title %}Создание группы{% endblock %}
{% block content %}
<div class="container py-5">
    <h1 style="text-align:center">{{ title }}</h1>
    <form action="{% url 'posts:create_group' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}

                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}<br>
        <button type="submit" class="btn btn-primary">Создать группу</button>
    </form>
</div>
{% endblock %}

blog/templates/posts/new_post.html
{% extends "base.html" %}
{% block title %}Создание поста{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Добавить пост</div>
            <div class="card-body">
                <form action="{% url 'posts:create_post' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group row my-3 p-3">
                            <label for="{{ field.id_for_label }}">
                                {{ field.label }}
                                {% if field.field.required %}
                                    <span class="required text-danger">*</span>
                                {% endif %}
                            </label>

                            {{ field }}

                            {% if field.errors %}
                                <div class="alert alert-danger">
                                    {{ field.errors }}
                                </div>
                            {% endif %}

                            {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                  {{ field.help_text|safe }}
                                </small>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Добавить пост
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post" action="{% url 'users:login' %}">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3" aria-required="{% if field.field.required %}true{% else %}false{% endif %}">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/users/logout.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
    {% load user_filters %}

    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">Зарегистрироваться</div>
                <div class="card-body">

                    {% if form.errors %}
                        {% for error in form.errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post" action="{% url 'users:signup' %}">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}

                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        Зарегистрироваться
                    </button>
                </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
    </div> <!-- row -->

{% endblock %}